# Generated by Django 3.1.4 on 2020-12-29 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0004_auto_20201229_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadsettings',
            name='mode',
            field=models.CharField(choices=[('normal', 'normal'), ('reverse', 'reverse'), ('random', 'random')], default='reversed', max_length=10),
        ),
    ]
