# Generated by Django 3.1.4 on 2020-12-29 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0006_auto_20201229_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadsettings',
            name='algorithm',
            field=models.CharField(choices=[('bfs', 'bfs'), ('dfs', 'dfs')], default='dfs', max_length=4),
        ),
    ]
