# Generated by Django 3.1.4 on 2020-12-29 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0007_uploadsettings_algorithm'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateCell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(choices=[('normal', 'normal'), ('reverse', 'reverse'), ('random', 'random')], max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='uploadsettings',
            name='algorithm',
            field=models.CharField(choices=[('bfs', 'bfs'), ('dfs', 'dfs')], default='bfs', max_length=4),
        ),
    ]
