# Generated by Django 3.1.4 on 2020-12-29 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0008_auto_20201229_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatecell',
            name='answer',
            field=models.CharField(max_length=100),
        ),
    ]
