# Generated by Django 3.1.4 on 2020-12-29 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0009_auto_20201229_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadsettings',
            name='timeout',
            field=models.TextField(default='-1', max_length=100),
        ),
        migrations.AddField(
            model_name='uploadsettings',
            name='use_self_filled',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], default='True', max_length=10),
        ),
        migrations.AlterField(
            model_name='uploadsettings',
            name='algorithm',
            field=models.CharField(choices=[('bfs', 'bfs'), ('dfs', 'dfs'), ('a-star', 'a-star'), ('b-star', 'b-star'), ('c-star', 'c-star')], default='c-star', max_length=6),
        ),
        migrations.AlterField(
            model_name='uploadsettings',
            name='mode',
            field=models.CharField(choices=[('normal', 'normal'), ('reverse', 'reverse'), ('random', 'random')], default='random', max_length=10),
        ),
    ]
